angular.module('moviesSkyDriveCtrl',[])
.controller('moviesSkyDriveCtrl',function($scope){
	$scope.navs=[
		{name:'咨询',href:'#'},
		{name:'电影',href:'/moviesShow'},
		{name:'电视剧',href:'#'},
		{name:'求片区',href:'#'},
		{name:'更多+',href:'#'}
	]
})
